// List of 365 quotes
final List<String> quotes = [
  'You don’t need to hit rock bottom to rise—start today and avoid the fall.',
  'The change you seek begins when you decide to no longer wait.',
  'The hardest part is not the journey, it’s the decision to begin.',
  'Discipline today will give you a life you never thought possible.',
  'The life you want is not waiting for you; it’s built one choice at a time.',
  'Procrastination steals your future, start building it today.',
  'You don’t need time, you need commitment.',
  'Purpose isn’t found, it’s created by the actions you take.',
  'Discipline is the foundation of freedom.',
  'Stop waiting for motivation; create it with every step you take.',
  'You are only as strong as your habits.',
  'Waiting for the right time means you’re wasting the only time you have.',
  'Change doesn’t start tomorrow, it starts today.',
  'Your best self lies just beyond your comfort zone—embrace the challenge.',
  'The only time that matters is the time you’re willing to commit to right now.',
  'If you want it bad enough, you’ll find a way. If not, you’ll find an excuse.',
  'Don’t wait for things to get easier—make them easier by working harder.',
  'Your future doesn’t depend on luck, it depends on your actions today.',
  'The pain of discipline is nothing compared to the pain of regret.',
  'What you do today will echo in your future.',
  'Discipline is choosing between what you want now and what you want most.',
  'Every action today is a seed planted for tomorrow’s harvest.',
  'Don’t wait for a miracle—be the miracle you seek.',
  'The future you dream of is created by the steps you take today.',
  'Don’t let fear of the unknown stop you—take the first step anyway.',
  'Success isn’t given to those who wait, but to those who grind relentlessly.',
  'Growth is painful, but it’s worth every ounce of discomfort.',
  'Start now, not later. Tomorrow is not promised.',
  'The moment you stop making excuses is the moment your life changes.',
  'The only person who can hold you back is yourself. Let go.',
  'Every choice you make today shapes who you become tomorrow.',
  'True progress happens when you commit to the process, not the outcome.',
  'Change doesn’t require motivation; it requires action.',
  'Your future is determined by what you do today, not by what you plan to do tomorrow.',
  'Discipline is doing what you need to do, even when you don’t feel like it.',
  'Don’t wait for the perfect moment—create it with your effort.',
  'The difference between who you are and who you want to be is what you do today.',
  'Focus on the process, not the reward. Results will follow.',
  'Every day is a new opportunity to be better than yesterday.',
  'Start small, stay consistent, and success will follow.',
  'Your greatest asset is your ability to stay disciplined when others falter.',
  'Stop letting distractions take you away from what really matters.',
  'Every sacrifice you make today is a step closer to your goals.',
  'Commitment is the bridge between goals and accomplishment.',
  'The time you invest today is the reward you get tomorrow.',
  'When you focus on progress, the outcome will take care of itself.',
  'Success is built on the consistency of small, purposeful actions.',
  'Every small step counts when it’s taken with purpose.',
  'Don’t just wish for success—work for it with every ounce of your being.',
  'Procrastination only prolongs the pain of unachieved dreams.',
  'The journey is long, but the reward is worth it. Stay the course.',
  'You can’t change the past, but you have the power to change today.',
  'Discipline isn’t something you have; it’s something you build.',
  'The only way to predict your future is to create it today.',
  'Success isn’t a destination, it’s a way of life.',
  'Time waits for no one, so make every moment count.',
  'Don’t let the fear of failure stop you—use it as fuel to push harder.',
  'The road to greatness is paved with relentless focus.',
  'What you do in the dark will eventually show in the light.',
  'You are in control of your life, and it starts with your decisions today.',
  'Success doesn’t come by wishing, it comes by working.',
  'Every day is a new opportunity to rewrite your story.',
  'Success is the sum of all the little decisions you make daily.',
  'The best time to start was yesterday. The second best time is now.',
  'Your potential is unlocked by action, not waiting.',
  'The difference between dreams and reality is the work you put in today.',
  'You can’t become something new without doing something new.',
  'Be so disciplined that excuses don’t stand a chance.',
  'The greatest victories are won in the smallest moments.',
  'Focus on becoming the best version of yourself, one decision at a time.',
  'There’s no time like the present to start working toward your future.',
  'Don’t wait for the perfect opportunity—create it with your effort.',
  'Action is the difference between where you are and where you want to be.',
  'Make your decisions today as if your future self is watching.',
  'Your life is a reflection of your daily habits—change them, change your life.',
  'You are only as strong as the discipline you practice every day.',
  'Don’t wait for a chance, create your own opportunities.',
  'Success is the byproduct of relentless focus and hard work.',
  'The fear of regret should drive you more than the fear of failure.',
  'Don’t just survive today—thrive with purpose.',
  'What you choose to focus on will determine your future.',
  'You can’t change your destiny without changing your daily habits.',
  'The future belongs to the doers, not the dreamers.',
  'Every action you take today builds the future you’ll live tomorrow.',
  'If you want success, stop waiting for it to come to you—go after it.',
  'There’s no shortcut to success—only hard work and commitment.',
  'Change your mindset, change your habits, change your life.',
  'Every day is a chance to reset and refocus on your goals.',
  'Be fearless in the pursuit of your goals.',
  'Success isn’t about perfection, it’s about progress.',
  'The time for change is not tomorrow, it’s today.',
  'Discipline gives you the freedom to live the life you want.',
  'Success doesn’t find you, you find it through hard work and focus.',
  'What you do today will determine what you have tomorrow.',
  'You won’t always be motivated, but you can always be disciplined.',
  'Start today, not tomorrow—your future is waiting for you.',
  'You can’t become a champion by standing still. Move forward.',
  'Time is your most precious resource; use it wisely.',
  'Commit to the process, and the results will take care of themselves.',
  'What you choose today shapes who you become tomorrow.',
  'Your habits today will create your future success.',
  'Every moment spent waiting is a moment wasted. Act now.',
  'If you want different results, do something different today.',
  'Discipline today builds the life you’ve always dreamed of.',
  'Success is earned through consistent hard work, not overnight luck.',
  'Your future self is built by the choices you make today.',
  'Stop waiting for a miracle; become your own miracle through effort.',
  'The harder you work today, the easier tomorrow becomes.',
  'Discipline today is the foundation of a better tomorrow.',
  'Focus on what’s within your control, and everything else will fall into place.',
  'The greatest achievement starts with the courage to begin.',
  'You can have excuses or you can have results, but you can’t have both.',
  'Start with purpose, and your success will follow.',
  'Stop wishing, start doing. The time for action is now.',
  'Discipline isn’t a choice—it’s a necessity for growth.',
  'Be patient with the process, but relentless with your work.',
  'Success is the result of disciplined actions repeated over time.',
  'Consistency is more important than perfection.',
  'The future belongs to those who act today.',
  'Don’t wait for an opportunity—create one.',
  'Your habits will either take you closer to your dreams or farther from them.',
  'Small changes lead to massive transformations over time.',
  'The road to success is always under construction—stay focused.',
  'Discipline is the art of making the right choice over and over again.',
  'Start now—don’t wait for the perfect moment, make it perfect with action.',
  'You can’t change your destiny until you change your actions today.',
  'Your potential is limitless, but only if you work for it.',
  'Focus is the compass that will guide you to success.',
  'Don’t let setbacks stop you; let them fuel your comeback.',
  'Every day is a new chance to create the life you want.',
  'You can’t control everything, but you can control your effort.',
  'The difference between who you are and who you want to be is discipline.',
  'Great things don’t come from comfort zones. Step out.',
  'Success isn’t a choice, it’s a result of consistent effort.',
  'Success isn’t about waiting for the storm to pass, it’s about learning to thrive in it.',
  'If you want to achieve greatness, you have to start somewhere.',
  'Nothing worth having comes easy—put in the work.',
  'Discipline isn’t a punishment, it’s the key to your freedom.',
  'Stop waiting for opportunities, start creating them.',
  'Success comes from mastering the mundane tasks, day in and day out.',
  'The pain of regret lasts longer than the pain of discipline.',
  'Small steps lead to big changes—don’t underestimate them.',
  'You will never regret hard work, but you might regret the time you wasted.',
  'The time to act is now—don’t put your life on hold.',
  'Consistency beats intensity when it comes to achieving success.',
  'The key to your future lies in your ability to stay disciplined today.',
  'When you feel like quitting, remember why you started.',
  'Your future will be shaped by the actions you take today.',
  'Success doesn’t come from what you do occasionally, it comes from what you do consistently.',
  'What you do today will determine your tomorrow—make it count.',
  'Every day is an opportunity to become a better version of yourself.',
  'True transformation happens when you commit to the process, not just the result.',
  'It’s not the perfect moment that makes a difference—it’s your decision to act.',
  'Your focus today will shape your life tomorrow.',
  'You don’t need more time, you need more discipline.',
  'Success is not for the lazy; it’s for the disciplined.',
  'Don’t let your dreams die from a lack of discipline.',
  'You don’t have to be great to start, but you have to start to be great.',
  'Every action counts. Make sure they are pushing you toward your goal.',
  'Be so focused on your goals that distractions don’t even get your attention.',
  'Stop waiting for motivation—build it with every step you take.',
  'What you do today defines what you achieve tomorrow.',
  'Dream big, act bigger.',
  'Success doesn’t come to you; you have to go to it.',
  'Take control of today, and tomorrow will take care of itself.',
  'The greatest victory is the one you win over your own hesitation.',
  'Time doesn’t wait for anyone—act now and own your future.',
  'Hard work beats talent when talent doesn’t work hard.',
  'Your goals are only as far away as your determination to reach them.',
  'Success is built on the willingness to keep going when others quit.',
  'The price of success is effort—and you can afford it.',
  'Your commitment today is the foundation of your success tomorrow.',
  'Every setback is a setup for a greater comeback.',
  'Great things never come from waiting for the perfect moment.',
  'Do what others won’t today, so you can live how others can’t tomorrow.',
  'Discipline is doing what needs to be done, even when you don’t feel like it.',
  'Hard work and focus can turn the impossible into the possible.',
  'Don’t wait for the stars to align—align your actions with your goals.',
  'Success starts with making the decision to act today.',
  'Your efforts today are the seeds of your success tomorrow.',
  'You don’t have to be perfect, just consistent.',
  'A goal without action is just a dream waiting to be forgotten.',
  'Take one step forward every day—even on the days it’s hard.',
  'The difference between where you are and where you want to be is discipline.',
  'Don’t be afraid of failure—be afraid of not trying at all.',
  'Focus on your own growth, and success will follow.',
  'Discipline today creates the freedom you’ll enjoy tomorrow.',
  'Your potential is only limited by the effort you put in.',
  'Greatness doesn’t come from waiting; it comes from doing.',
  'Every day is a chance to make a decision that moves you closer to your dreams.',
  'Your future is written by the choices you make today.',
  'Discipline is the bridge between your goals and your success.',
  'Don’t just wish for success, work for it every single day.',
  'You can achieve anything, but only if you’re willing to work for it.',
  'The best time to plant a tree was 20 years ago; the second best time is today.',
  'Small efforts compounded over time lead to big results.',
  'Take control of your day, and you’ll take control of your life.',
  'Focus on the task at hand, and the results will come.',
  'Success is a journey, not a destination—commit to the journey.',
  'The best investment you can make is in your own growth.',
  'Discipline isn’t just about control—it’s about freedom.',
  'What you do today matters more than what you’ll do tomorrow.',
  'Success is earned by those who show up, every single day.',
  'You are capable of more than you realize, but only if you commit to it.',
  'Success is a product of hard work, consistency, and determination.',
  'Action is the antidote to fear—take the first step.',
  'What you do today shapes your tomorrow—make it count.',
  'The best way to predict your future is to create it.',
  'The grind doesn’t stop, and neither should you.',
  'It doesn’t matter how slowly you go, as long as you don’t stop.',
  'The road to success is paved with continuous effort.',
  'No dream is too big if you’re willing to put in the work.',
  'Don’t wait for permission to succeed—take what’s yours.',
  'Discipline is the foundation upon which success is built.',
  'You won’t regret the work you put in today, but you might regret the time you wasted.',
  'Stop waiting for motivation; create it through action.',
  'The way you spend today is the way you’ll spend your life.',
  'Don’t wait for the perfect opportunity—make every opportunity perfect.',
  'Your destiny is shaped by what you do today, not tomorrow.',
  'Success is not for the lazy; it’s for those who persevere.',
  'Start now. It’s the only time that truly matters.',
  'The road to success is always under construction—keep building.',
  'The only way to reach your goals is by taking consistent action.',
  'Dreams don’t work unless you do.',
  'What you do today will be the foundation for your tomorrow’s success.',
  'Success doesn’t wait for you to feel ready—it comes when you’re willing to act.',
  'No one ever achieved greatness by waiting for things to change.',
  'Stay focused on the process, and the results will follow.',
  'Do something today that your future self will thank you for.',
  'The difference between where you are and where you want to be is the work you put in.',
  'Discipline is the difference between where you are and where you want to go.',
  'Don’t wait for a sign—be the sign that your time is now.',
  'Success is not owned, it’s rented—and the rent is due every day.',
  'Today is a new opportunity to be better than you were yesterday.',
  'Great things don’t happen overnight; they happen over time.',
  'The secret to success is consistency in the face of challenges.',
  'Start with faith in yourself, and the discipline will follow.',
  'Success is not a destination; it’s the journey of constant improvement.',
  'A dream without action is just a wish. Make it real today.',
  'The difference between a dream and reality is the work you’re willing to put in.',
  'What you do today shapes the person you become tomorrow.',
  'No dream is too big when you break it into disciplined actions.',
  'Discipline is not a restriction; it’s the path to freedom.',
  'The time for change is not next week, it\'s today.',
  'Every decision you make today creates your future tomorrow.',
  'Stay focused on your journey—your time will come.',
  'Every step, no matter how small, is progress. Keep moving forward.',
  'Success is the result of doing the things others won’t do.',
  'Action today means success tomorrow—don’t wait for the perfect moment.',
  'Discipline is your greatest ally on the road to success.',
  'Success is a decision, not a chance. Choose it today.',
  'You are the creator of your own success story—start writing it today.',
  'The secret to achieving greatness is consistency, not perfection.',
  'Focus on building habits today that will shape your future.',
  'You’ll regret the things you didn’t do far more than the things you tried.',
  'The key to success is to focus on goals, not obstacles.',
  'The work you put in today will define your success tomorrow.',
  'Success is earned in the moments when you choose discipline over comfort.',
  'Push yourself beyond the limits of your comfort zone. That’s where growth happens.',
  'No matter how small, every step forward is progress.',
  'Success isn’t for the lucky; it’s for those who take action.',
  'The difference between where you are and where you want to be is the work you’re willing to do.',
  'Your consistency today guarantees your success tomorrow.',
  'The only limit is the one you place on your own effort.',
  'Every challenge is an opportunity to grow. Take it.',
  'Success doesn’t come to those who wait. It comes to those who act.',
  'Discipline is the bridge between goals and achievement.',
  'The price of greatness is hard work. Are you willing to pay it?',
  'Don’t wait for the right time—make it the right time with your actions.',
  'Every small step you take today leads to monumental growth.',
  'What you do today sets the stage for your tomorrow’s success.',
  'Your future is shaped by what you do in the present moment.',
  'The effort you put in today determines the success you have tomorrow.',
  'You don’t need motivation, you need consistency and action.',
  'Discipline is the tool that turns your dreams into reality.',
  'Success is the sum of small efforts, repeated day in and day out.',
  'Procrastination is the enemy of progress. Take action now.',
  'Don’t settle for what you have—strive for what you can achieve.',
  'Growth comes when you push beyond your comfort zone.',
  'The journey to success begins with the courage to take that first step.',
  'Discipline today is the reward you’ll enjoy tomorrow.',
  'The only way to achieve your goals is to take consistent, focused action.',
  'Success is a habit, not a one-time event.',
  'If you want to change your life, change your habits today.',
  'You’re only one decision away from a completely different life.',
  'The actions you take today will create the life you’ll live tomorrow.',
  'Success is found in the courage to keep going, even when it gets hard.',
  'Small efforts lead to big results—stay consistent.',
  'Hard work is the shortcut to success.',
  'Focus on the process, and the results will take care of themselves.',
  'Success starts with discipline and is sustained by consistency.',
  'Don’t wait for opportunities to come to you—create them.',
  'What you do today will build the foundation for your tomorrow.',
  'Consistency and effort are your greatest tools for success.',
  'The grind may be tough, but the rewards are worth it.',
  'What you achieve tomorrow is determined by what you do today.',
  'Every effort you make today compounds into success tomorrow.',
  'Make today the day you start building your future.',
  'The work you put in today becomes the success you enjoy tomorrow.',
  'Success is not a matter of chance, it’s a matter of choice and consistent effort.',
  'What you do today will decide who you become tomorrow.',
  'Success requires focus, commitment, and action—do it now.',
  'The road to success is paved with persistence and hard work.',
  'The time to act is now—stop waiting for the perfect moment.',
  'Small steps taken consistently lead to massive success.',
  'You are the sum of your daily actions. What are you building today?',
  'Discipline is the silent force behind every great achievement.',
  'Start where you are, use what you have, and do what you can.',
  'Every choice you make today sets the foundation for tomorrow’s success.',
  'If you’re not willing to work for it, don’t expect to achieve it.',
  'The best time to start was yesterday. The second best time is today.',
  'The difference between where you are and where you want to be is in your actions.',
  'The future belongs to those who act, not those who wait.',
  'Commit to the process, and the results will follow.',
  'Success is the result of doing things others won’t do.',
  'Discipline today gives you freedom tomorrow.',
  'Small sacrifices today create big rewards tomorrow.',
  'Every step forward, no matter how small, is still progress.',
  'Success isn’t something you wait for; it’s something you work for.',
  'Consistency will always beat talent when talent doesn’t work hard enough.',
  'Don’t just wait for success—chase it down with relentless effort.',
  'Focus on what you can control today, and everything else will fall into place.',
  'Success requires taking action every single day.',
  'What you do today is the foundation of your success tomorrow.',
  'Every minute spent planning is a minute spent on your future success.',
  'Your habits today will create your results tomorrow.',
  'Success doesn’t happen by accident—it happens through intentional effort.',
  'You have the power to create the life you want, one decision at a time.',
  'Make today the day you take action toward your dreams.',
  'Don’t let fear of failure hold you back—use it as motivation.',
  'Every small step forward is still a step closer to your goals.',
  'Discipline is not about limiting yourself; it’s about empowering yourself to achieve more.',
  'Success starts when you make the decision to act, not when the conditions are perfect.',
  'What you do today sets the tone for your future. Make it count.',
  'If you want to succeed, stop talking and start doing.',
  'The road to success is long, but every step is worth it.',
  'Success is the result of consistent effort over time.',
  'To achieve your dreams, you must first wake up and work for them.',
  'Success is built on the small actions you take daily.',
  'Discipline is what separates successful people from those who only dream.',
  'Every day is a new chance to make progress toward your goals.',
  'The difference between where you are and where you want to be is in your work ethic.',
  'You won’t achieve anything without putting in the work today.',
  'The road to success is paved with persistence, not perfection.',
  'Focus on the small wins, and the big wins will follow.',
  'Success is a mindset that requires daily action to manifest.',
  'Discipline makes the impossible possible.',
  'You won’t get what you want if you don’t act on what you need.',
  'Greatness is achieved by those who are willing to keep going when others quit.',
  'The future is created by the choices you make today.',
  'Make today the day you commit to the process.',
  'Success isn’t given—it’s earned through discipline and action.',
  'You can’t achieve your dreams without first doing the work.',
  'The only limit to your success is your willingness to act.',
  'Success is not for those who wait. It’s for those who act decisively.',
  'Discipline is what turns your dreams into reality.',
  'The best investment you can make is in your own growth and development.',
  'Don’t wait for opportunities to come to you—create them.',
  'Success is the result of relentless focus and hard work.',
  'What you do today will determine what you can achieve tomorrow.',
  'You can’t climb the mountain of success without first taking the first step.',
  'Your future is decided by the actions you take today, not tomorrow.',
  'To achieve great things, you must first decide to work for them.',
  'Don’t wait for permission—take what you deserve with hard work.',
  'Success is the result of staying disciplined, no matter the circumstances.'
];
